/**
 * Stage 1 W4 Track B Run 1 — seed 5 hero images в Payload Media collection.
 *
 * Идемпотентен: для каждого item ищем по `filename`, если уже есть — skip
 * (Payload UI / админ оператора не перезатираем). Если нет — создаём с
 * filePath (Payload сам прогонит через sharp + создаст thumb/card/hero/og
 * variants per Media.ts upload.imageSizes config).
 *
 * Используется на staging/prod на Wave 1 (W5+) когда cms подключает hero
 * images к Services (heroImage relation). Run 1 deliverable от cms — этот
 * скрипт + 5 файлов в site/public/uploads/stage1-w4/.
 *
 * Запуск:
 *   pnpm tsx --require=./scripts/_payload-cjs-shim.cjs --env-file=.env.local scripts/seed-stage1-media.ts
 *   OBIKHOD_SEED_CONFIRM=yes pnpm tsx --require=./scripts/_payload-cjs-shim.cjs scripts/seed-stage1-media.ts  # prod
 *
 * Safety-gate: на prod без OBIKHOD_SEED_CONFIRM=yes — exit без изменений.
 *
 * Spec: specs/EPIC-SEO-CONTENT-FILL/US-1-pillars-pilot/intake.md (Track B Run 1).
 */
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import { getPayload } from 'payload'
import config from '../payload.config.js'

// site/public/uploads/stage1-w4/prompts-batch.json — single source of truth.
const REPO_ROOT = resolve(__dirname, '..')
const BATCH_PATH = resolve(REPO_ROOT, 'public/uploads/stage1-w4/prompts-batch.json')

type BatchItem = {
  id: string
  page: string
  fixture: string
  outFile: string
  publicPath: string
  alt: string
}

type Batch = { items: BatchItem[] }

type SeedStatus = 'created' | 'skipped' | 'error'
type SeedResult = { id: string; status: SeedStatus; message: string }

function isProdHost(): boolean {
  const uri = process.env.DATABASE_URI ?? ''
  return /45\.153\.190\.107|obikhod\.ru/.test(uri) || process.env.OBIKHOD_ENV === 'production'
}

function gateProd(): void {
  if (!isProdHost()) return
  if (process.env.OBIKHOD_SEED_CONFIRM !== 'yes') {
    console.error('✗ prod-host detected; require OBIKHOD_SEED_CONFIRM=yes to proceed.')
    process.exit(1)
  }
}

async function seedItem(
  payload: Awaited<ReturnType<typeof getPayload>>,
  item: BatchItem,
): Promise<SeedResult> {
  // Path may live in repo's site/ root (Track B Run 1 generates here).
  const absPath = resolve(REPO_ROOT, item.outFile.replace(/^site\//, ''))
  if (!existsSync(absPath)) {
    return { id: item.id, status: 'error', message: `file not found: ${absPath}` }
  }
  const filename = `${item.id}.jpg`

  // Idempotent: skip если media с таким filename уже есть.
  const existing = await payload.find({
    collection: 'media',
    where: { filename: { equals: filename } },
    limit: 1,
    depth: 0,
  })
  if (existing.docs.length > 0) {
    return {
      id: item.id,
      status: 'skipped',
      message: `already in Media (id=${(existing.docs[0] as { id: string | number }).id})`,
    }
  }

  try {
    const created = await payload.create({
      collection: 'media',
      data: {
        alt: item.alt,
        caption: `Stage 1 W4 hero — ${item.page}`,
        // Stage 1 W4 — generated by fal.ai → license=proprietary (наша модель).
        license: 'proprietary',
        // EXIF GPS отсутствует для AI-генерации.
        geoLocation: null,
      },
      file: {
        data: readFileSync(absPath),
        mimetype: 'image/jpeg',
        name: filename,
        size: readFileSync(absPath).byteLength,
      },
      overrideAccess: true,
    })
    return {
      id: item.id,
      status: 'created',
      message: `Media id=${(created as { id: string | number }).id}, filename=${filename}`,
    }
  } catch (e) {
    return {
      id: item.id,
      status: 'error',
      message: e instanceof Error ? e.message : String(e),
    }
  }
}

async function main(): Promise<void> {
  gateProd()
  const batch = JSON.parse(readFileSync(BATCH_PATH, 'utf-8')) as Batch

  console.log(`Stage 1 W4 media seed: ${batch.items.length} item(s)`)
  const payload = await getPayload({ config })

  const results: SeedResult[] = []
  for (const item of batch.items) {
    const r = await seedItem(payload, item)
    const icon = r.status === 'created' ? '✓' : r.status === 'skipped' ? '⏭' : '✗'
    console.log(`  ${icon} ${r.id} · ${r.status} · ${r.message}`)
    results.push(r)
  }

  const errors = results.filter((r) => r.status === 'error')
  console.log('')
  if (errors.length === 0) {
    console.log(
      `✓ Done · created=${results.filter((r) => r.status === 'created').length}, skipped=${results.filter((r) => r.status === 'skipped').length}`,
    )
    process.exit(0)
  }
  console.error(`✗ Done with errors · ${errors.length}/${results.length}`)
  process.exit(1)
}

main().catch((err) => {
  console.error('✗ Fatal:', err)
  process.exit(1)
})
